// src/config/wynikiColumns.js
export const wynikiColumns = [
    { id: "ID", label: "ID", minWidth: 70, hidden: true },
    { id: "NrSample", label: "Nr Próbki", minWidth: 120, sticky: "left" },
    { id: "Batch", label: "Partia", minWidth: 150 },
    { id: "ItemCode", label: "Indeks", minWidth: 150 },
    { id: "ItemName", label: "Nazwa Produktu", minWidth: 250 },
    { id: "WhsCode", label: "Magazyn SAP", minWidth: 100 },
    { id: "NikoM", label: "MOC [mg/ml]", minWidth: 80 },
    { id: "NikoPR1", label: "Próbka nr. 1", minWidth: 80 },
    { id: "NikoPR2", label: "Próbka nr. 2", minWidth: 80 },
    { id: "AvgNiko", label: "Średnia", minWidth: 80 },
    { id:"AccCriterium1",label:"Kryterium akceptacji 1"},
    { id:"AccCriterium2",label:"Kryterium akceptacji 2"},
    { id:"AssCriterium1",label:"Ocena zgodności wyniku 1 z kryterium akceptacji", minWidth: 100, wrap: true  },
    { id:"AssCriterium2",label:"Ocena zgodności wyniku 2 z kryterium akceptacji", minWidth: 100, wrap: true  },
    { id: "ResultGC", label: "Wynik GC", minWidth: 120 },
    { id:"PersonWerNik", label:"Osoba weryfikująca wyniki nikotyny", minWidth: 100, wrap: true },
    { id:"EvaluationGC",label:"Ocena zgodności wyniku GC", minWidth: 100, wrap: true },
    { id:"ResultWhs",label:"Wynik sprawdzenia na magazynie", minWidth: 100, wrap: true },
    { id: "StatusSample", label: "Status", minWidth: 120 },
    { id: "PersonUnloc", label: "Osoba zwalniająca", minWidth: 100 },
    { id:"DateUnloc", label:"Data odblokowania SAP", minWidth: 100, wrap: true  },
    { id: "Comment", label: "Komentarz", minWidth: 200 },
];